# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
