# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_alias'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posted_quotes', to='login.User'),
            preserve_default=False,
        ),
    ]
